{"name": "test_contact_us_order_reference_validation_for_empty_message", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "self = <test_contactform.ContactUsFormTestSuite testMethod=test_contact_us_order_reference_validation_for_empty_message>\n\n    def test_contact_us_order_reference_validation_for_empty_message(self):\n    \tself.homescreen = HomeScreen(self.driver)\n    \tself.homescreen.click_contact_us_button()\n    \n    \tself.contact_us_form = ContactUsForm(self.driver)\n    \tself.contact_us_form.select_subject_heading(strings.subject)\n    \tself.contact_us_form.write_email_address(strings.valid_email)\n    \tself.contact_us_form.write_message(strings.valid_message)\n    \tself.contact_us_form.click_send_button()\n>   \tself.contact_us_form.validate_error_message(strings.missing_order_reference)\n\ntestcases\\test_contactform.py:77: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npageobjects\\contactusform.py:82: in validate_error_message\n    By.XPATH, \"//li[contains(text(), '{0}')]\".format(error))))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"7da78818f4f22424f9874f0f7d5f55b5\")>\nmethod = <selenium.webdriver.support.expected_conditions.visibility_of_element_located object at 0x0000018A4C321080>\nmessage = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value is not False.\"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:80: TimeoutException"}, "steps": [{"name": "Click Contact Us Button", "status": "passed", "start": 1646597344630, "stop": 1646597345368}, {"name": "Select a Subject Heading", "status": "passed", "parameters": [{"name": "subject", "value": "'Webmaster'"}], "start": 1646597345482, "stop": 1646597345508}, {"name": "Input an Email Address", "status": "passed", "parameters": [{"name": "email", "value": "'test@test.com'"}], "start": 1646597345508, "stop": 1646597345546}, {"name": "Input a Message", "status": "passed", "parameters": [{"name": "message", "value": "'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec molestie rutrum ligula ut viverra. Mauris fringilla ex nec ultrices gravida. Nam vestibulum tempus arcu eu iaculis. Vestibulum suscipit pretium ligula, eu eleifend tortor maximus non. Duis id cursus sem. Morbi sit amet pharetra ante, sit amet vulputate velit. Integer aliquam ex ipsum, vel volutpat velit dignissim sit amet. Proin malesuada ut augue in sollicitudin. Aenean aliquet metus eget commodo fringilla. Cras in pulvinar laoreet.'"}], "start": 1646597345546, "stop": 1646597346270}, {"name": "Click Send button", "status": "passed", "start": 1646597346270, "stop": 1646597347082}, {"name": "Validate a Contact Us Form error message", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"C:\\Users\\OneMaco\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\OneMaco\\Desktop\\Jobsity\\Jobsity-QAChallenge\\AutomationPracticeFramework\\pageobjects\\contactusform.py\", line 82, in validate_error_message\n    By.XPATH, \"//li[contains(text(), '{0}')]\".format(error))))\n  File \"C:\\Users\\OneMaco\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "parameters": [{"name": "error", "value": "'The order reference cannot be blank.'"}], "start": 1646597347082, "stop": 1646597357252}], "start": 1646597337361, "stop": 1646597359351, "uuid": "d87a3636-6727-4d08-906c-8ebbad0ca6d4", "historyId": "d0711ce4593eca21007a1d2ca32be3b1", "testCaseId": "69b65a0e2c42a90ce8dcfe3cc32676f4", "fullName": "testcases.test_contactform.ContactUsFormTestSuite#test_contact_us_order_reference_validation_for_empty_message", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_contactform"}, {"name": "subSuite", "value": "ContactUsFormTestSuite"}, {"name": "host", "value": "DESKTOP-SSGALID"}, {"name": "thread", "value": "30320-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_contactform"}]}